use anchor_lang::prelude::*;
use crate::errors::CoordinationError;
use groth16_solana::groth16::Groth16Verifier;

// Verifying key generated by circuits/bool_range/export_vk.js after trusted setup.
// Re-run circuits/bool_range/setup.sh to regenerate.
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../circuits/bool_range/verifying_key.rs"));

/// Verifies a Groth16 range proof that the committed guess is ∈ {0, 1}.
///
/// The circuit proves two things:
///   1. guess ∈ {0, 1}  (boolean constraint)
///   2. SHA-256(guess_byte || salt_bytes) == commitment  (commitment binding)
///
/// `proof_a` must be the **negated** G1 point. The client computes -A before
/// submitting; the verifier receives it pre-negated. This is a requirement of
/// the groth16-solana pairing equation.
///
/// The 32-byte `commitment` is split into two 128-bit field elements (high and
/// low halves) as public inputs, since 256-bit values exceed the BN254 field.
pub fn verify_bool_range_proof(
    proof_a: &[u8; 64],
    proof_b: &[u8; 128],
    proof_c: &[u8; 64],
    commitment: &[u8; 32],
) -> Result<()> {
    let public_inputs = split_commitment(commitment);

    let mut verifier = Groth16Verifier::new(
        proof_a,
        proof_b,
        proof_c,
        &public_inputs,
        &VERIFYING_KEY,
    )
    .map_err(|_| error!(CoordinationError::InvalidRangeProof))?;

    verifier
        .verify()
        .map_err(|_| error!(CoordinationError::InvalidRangeProof))
}

/// Splits a 32-byte commitment into two 128-bit BN254 field elements.
///
/// Each half is zero-padded to 32 bytes (big-endian), placing the 16 data bytes
/// in the low bytes. 128-bit values are always within the BN254 scalar field.
fn split_commitment(commitment: &[u8; 32]) -> [[u8; 32]; 2] {
    let mut high = [0u8; 32];
    let mut low = [0u8; 32];
    high[16..].copy_from_slice(&commitment[..16]);
    low[16..].copy_from_slice(&commitment[16..]);
    [high, low]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn split_puts_high_bytes_in_first_element() {
        let mut commitment = [0u8; 32];
        for i in 0..32u8 {
            commitment[i as usize] = i + 1;
        }
        let [high, low] = split_commitment(&commitment);

        // High: first 16 commitment bytes in the low 16 bytes of the field element
        assert_eq!(&high[..16], &[0u8; 16], "high element must be zero-padded");
        assert_eq!(&high[16..], &commitment[..16]);

        // Low: last 16 commitment bytes in the low 16 bytes of the field element
        assert_eq!(&low[..16], &[0u8; 16], "low element must be zero-padded");
        assert_eq!(&low[16..], &commitment[16..]);
    }

    #[test]
    fn split_all_zeros_produces_zero_elements() {
        let [high, low] = split_commitment(&[0u8; 32]);
        assert_eq!(high, [0u8; 32]);
        assert_eq!(low, [0u8; 32]);
    }

    #[test]
    fn split_all_ones_round_trips() {
        let commitment = [0xffu8; 32];
        let [high, low] = split_commitment(&commitment);
        let mut reconstructed = [0u8; 32];
        reconstructed[..16].copy_from_slice(&high[16..]);
        reconstructed[16..].copy_from_slice(&low[16..]);
        assert_eq!(reconstructed, commitment);
    }
}
