import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { Coordination } from "../target/types/coordination";
import * as snarkjs from "snarkjs";
import { createHash } from "crypto";
import { ComputeBudgetProgram, Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram } from "@solana/web3.js";
import { assert } from "chai";
import * as path from "path";
import * as fs from "fs";

// ---------------------------------------------------------------------------
// ZK helpers
// ---------------------------------------------------------------------------

// Circuit artifacts are generated by `make setup`.
// Tests that require proofs are skipped if the artifacts are not present.
const WASM_PATH = path.resolve(__dirname, "../circuits/bool_range/bool_range_js/bool_range.wasm");
const ZKEY_PATH = path.resolve(__dirname, "../circuits/bool_range/circuit_final.zkey");
const ZK_READY = fs.existsSync(WASM_PATH) && fs.existsSync(ZKEY_PATH);

// BN254 scalar field prime
const BN254_P = 21888242871839275222246405745257275088696311157297823662689037894645226208583n;

function bigintToBuf32(n: bigint): Buffer {
  return Buffer.from(n.toString(16).padStart(64, "0"), "hex");
}

// Serializes snarkjs pi_a as a negated G1 point (64 bytes, big-endian X || -Y).
// groth16-solana requires proof_a to be negated before submission.
function serializeProofA(pi_a: string[]): number[] {
  const x = BigInt(pi_a[0]);
  const yNeg = BN254_P - BigInt(pi_a[1]);
  return Array.from(Buffer.concat([bigintToBuf32(x), bigintToBuf32(yNeg)]));
}

// Serializes snarkjs pi_b as a G2 point in altbn128 format:
// Xc1 (32) || Xc0 (32) || Yc1 (32) || Yc0 (32) = 128 bytes.
// snarkjs stores Fp2 coords as [c0, c1]; altbn128 precompile wants [c1, c0].
function serializeProofB(pi_b: string[][]): number[] {
  return Array.from(
    Buffer.concat([
      bigintToBuf32(BigInt(pi_b[0][1])), // X.c1
      bigintToBuf32(BigInt(pi_b[0][0])), // X.c0
      bigintToBuf32(BigInt(pi_b[1][1])), // Y.c1
      bigintToBuf32(BigInt(pi_b[1][0])), // Y.c0
    ])
  );
}

// Serializes snarkjs pi_c as a G1 point (64 bytes, big-endian X || Y).
function serializeProofC(pi_c: string[]): number[] {
  return Array.from(
    Buffer.concat([bigintToBuf32(BigInt(pi_c[0])), bigintToBuf32(BigInt(pi_c[1]))])
  );
}

// Converts a 32-byte salt buffer to 256 individual bit strings for the circom circuit.
// The circuit expects bits in big-endian order (MSB of first byte = index 0).
function saltToBits(salt: Buffer): string[] {
  const bits: string[] = [];
  for (const byte of salt) {
    for (let i = 7; i >= 0; i--) {
      bits.push(String((byte >> i) & 1));
    }
  }
  return bits;
}

interface CommitProof {
  commitment: number[]; // SHA-256(guess_byte || salt), 32 bytes
  proofA: number[];     // 64 bytes, negated G1
  proofB: number[];     // 128 bytes, G2
  proofC: number[];     // 64 bytes, G1
}

async function generateCommitProof(guess: 0 | 1, salt: Buffer): Promise<CommitProof> {
  const guessByte = Buffer.alloc(1, guess);
  const commitment = createHash("sha256")
    .update(Buffer.concat([guessByte, salt]))
    .digest();

  const commitmentHigh = BigInt("0x" + commitment.slice(0, 16).toString("hex"));
  const commitmentLow = BigInt("0x" + commitment.slice(16).toString("hex"));

  const input = {
    guess: String(guess),
    salt: saltToBits(salt),
    commitment_high: String(commitmentHigh),
    commitment_low: String(commitmentLow),
  };

  const { proof } = (await snarkjs.groth16.fullProve(input, WASM_PATH, ZKEY_PATH)) as any;

  return {
    commitment: Array.from(commitment),
    proofA: serializeProofA(proof.pi_a),
    proofB: serializeProofB(proof.pi_b),
    proofC: serializeProofC(proof.pi_c),
  };
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe("coordination", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.coordination as Program<Coordination>;

  const player1 = Keypair.generate();
  const player2 = Keypair.generate();

  const TOURNAMENT_ID = new BN(1);
  const STAKE = new BN(10_000_000); // 0.01 SOL
  const GUESS_HUMAN = 0;

  // Fixed salts — deterministic across test runs
  const p1Salt = Buffer.from(
    "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    "hex"
  );
  const p2Salt = Buffer.from(
    "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe",
    "hex"
  );

  let gameCounterPda: PublicKey;
  let tournamentPda: PublicKey;
  let gamePda: PublicKey;
  let p1ProfilePda: PublicKey;
  let p2ProfilePda: PublicKey;

  function tournamentIdBuf(): Buffer {
    return TOURNAMENT_ID.toArrayLike(Buffer, "le", 8);
  }

  // ---------------------------------------------------------------------------
  // Setup
  // ---------------------------------------------------------------------------

  before(async () => {
    for (const player of [player1, player2]) {
      const sig = await provider.connection.requestAirdrop(
        player.publicKey,
        2 * LAMPORTS_PER_SOL
      );
      await provider.connection.confirmTransaction(sig);
    }

    [gameCounterPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("game_counter")],
      program.programId
    );

    [tournamentPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("tournament"), tournamentIdBuf()],
      program.programId
    );
  });

  // ---------------------------------------------------------------------------
  // Initialize
  // ---------------------------------------------------------------------------

  it("initializes the program", async () => {
    await program.methods
      .initialize()
      .accounts({
        gameCounter: gameCounterPda,
        authority: provider.wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const counter = await program.account.gameCounter.fetch(gameCounterPda);
    assert.equal(counter.count.toString(), "0");
  });

  // ---------------------------------------------------------------------------
  // Tournament
  // ---------------------------------------------------------------------------

  it("creates a tournament", async () => {
    const now = Math.floor(Date.now() / 1000);
    await program.methods
      .createTournament(TOURNAMENT_ID, new BN(now - 60), new BN(now + 3600))
      .accounts({
        tournament: tournamentPda,
        authority: provider.wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    const t = await program.account.tournament.fetch(tournamentPda);
    assert.equal(t.tournamentId.toString(), TOURNAMENT_ID.toString());
    assert.isFalse(t.finalized);
  });

  // ---------------------------------------------------------------------------
  // Game setup
  // ---------------------------------------------------------------------------

  it("player 1 creates a game", async () => {
    const counter = await program.account.gameCounter.fetch(gameCounterPda);
    const gameId = counter.count;

    [gamePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("game"), (gameId as BN).toArrayLike(Buffer, "le", 8)],
      program.programId
    );

    [p1ProfilePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("player"), tournamentIdBuf(), player1.publicKey.toBuffer()],
      program.programId
    );

    await program.methods
      .createGame(STAKE)
      .accounts({
        game: gamePda,
        gameCounter: gameCounterPda,
        playerProfile: p1ProfilePda,
        tournament: tournamentPda,
        player: player1.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([player1])
      .rpc();

    const game = await program.account.game.fetch(gamePda);
    assert.equal(game.playerOne.toString(), player1.publicKey.toString());
    assert.equal(game.stakeLamports.toString(), STAKE.toString());
  });

  it("player 2 joins the game", async () => {
    [p2ProfilePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("player"), tournamentIdBuf(), player2.publicKey.toBuffer()],
      program.programId
    );

    await program.methods
      .joinGame()
      .accounts({
        game: gamePda,
        playerProfile: p2ProfilePda,
        tournament: tournamentPda,
        player: player2.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([player2])
      .rpc();

    const game = await program.account.game.fetch(gamePda);
    assert.equal(game.playerTwo.toString(), player2.publicKey.toString());
  });

  // ---------------------------------------------------------------------------
  // Commit — ZK proof required
  // ---------------------------------------------------------------------------

  it("rejects a commit with a garbage proof", async () => {
    const fakeCommitment = Array(32).fill(1);
    const garbageA = Array(64).fill(0);
    const garbageB = Array(128).fill(0);
    const garbageC = Array(64).fill(0);

    try {
      await program.methods
        .commitGuess(
          fakeCommitment as any,
          garbageA as any,
          garbageB as any,
          garbageC as any
        )
        .accounts({ game: gamePda, player: player1.publicKey })
        .signers([player1])
        .rpc();
      assert.fail("Expected InvalidRangeProof error");
    } catch (e: any) {
      assert.include(e.toString(), "InvalidRangeProof");
    }
  });

  (ZK_READY ? it : it.skip)("player 1 commits with a valid ZK proof", async () => {
    const { commitment, proofA, proofB, proofC } = await generateCommitProof(GUESS_HUMAN, p1Salt);

    // Groth16 verification costs ~200k CUs; set budget to 400k to be safe.
    const setBudget = ComputeBudgetProgram.setComputeUnitLimit({ units: 400_000 });

    await program.methods
      .commitGuess(
        commitment as any,
        proofA as any,
        proofB as any,
        proofC as any
      )
      .accounts({ game: gamePda, player: player1.publicKey })
      .preInstructions([setBudget])
      .signers([player1])
      .rpc();

    const game = await program.account.game.fetch(gamePda);
    assert.notDeepEqual(
      Array.from(game.p1Commit as any),
      Array(32).fill(0),
      "p1 commitment should be stored"
    );
  });

  (ZK_READY ? it : it.skip)("player 2 commits with a valid ZK proof", async () => {
    const { commitment, proofA, proofB, proofC } = await generateCommitProof(GUESS_HUMAN, p2Salt);

    const setBudget = ComputeBudgetProgram.setComputeUnitLimit({ units: 400_000 });

    await program.methods
      .commitGuess(
        commitment as any,
        proofA as any,
        proofB as any,
        proofC as any
      )
      .accounts({ game: gamePda, player: player2.publicKey })
      .preInstructions([setBudget])
      .signers([player2])
      .rpc();

    const game = await program.account.game.fetch(gamePda);
    // Both committed → state should now be Revealing
    assert.notDeepEqual(
      Array.from(game.p2Commit as any),
      Array(32).fill(0),
      "p2 commitment should be stored"
    );
  });

  // ---------------------------------------------------------------------------
  // Reveal + resolution
  // ---------------------------------------------------------------------------

  (ZK_READY ? it : it.skip)("both players reveal and the game resolves", async () => {
    const revealAccounts = {
      game: gamePda,
      p1Profile: p1ProfilePda,
      p2Profile: p2ProfilePda,
      tournament: tournamentPda,
      playerOneWallet: player1.publicKey,
      playerTwoWallet: player2.publicKey,
      systemProgram: SystemProgram.programId,
    };

    // Player 1 reveals
    await program.methods
      .revealGuess(GUESS_HUMAN, Array.from(p1Salt) as any)
      .accounts({ ...revealAccounts, player: player1.publicKey })
      .signers([player1])
      .rpc();

    // Player 2 reveals — triggers resolution
    await program.methods
      .revealGuess(GUESS_HUMAN, Array.from(p2Salt) as any)
      .accounts({ ...revealAccounts, player: player2.publicKey })
      .signers([player2])
      .rpc();

    const game = await program.account.game.fetch(gamePda);
    assert.equal(game.p1Guess, GUESS_HUMAN, "p1 should have guessed Human");
    assert.equal(game.p2Guess, GUESS_HUMAN, "p2 should have guessed Human");
    assert.notEqual(game.resolvedAt.toString(), "0", "game should be resolved");

    // Both guessed correctly in a homogenous match → both get 90% back
    // The tournament gets the remaining 10% from each player (20% total)
    const tournament = await program.account.tournament.fetch(tournamentPda);
    const expectedPrize = STAKE.muln(2).divn(10); // 2 * stake * 0.1
    assert.equal(
      tournament.prizeLamports.toString(),
      expectedPrize.toString(),
      "tournament should have received 10% from each player"
    );
  });
});
