// Regenerator for tests/fixtures/task-payout-vectors.json — the cross-impl
// contract that pins the payout formula across the TS oracle
// (sdk/task-outcome-oracle.ts), the Solana program (scoring.rs::compute_payment
// + resolve_challenge.rs::slash_bond), and ShillbotEscrow.sol
// (_computePayment + bond split). Run intentionally:
//
//   npx tsx scripts/gen-task-payout-vectors.ts
//
// The committed fixture is verified by:
//   - tests/harness/shillbot-surfaces.unit.test.ts  (TS drift guard)
//   - programs/shillbot/src/scoring.rs  #[test] payout_vectors  (Rust payment/fee)
//   - evm/test/ShillbotEscrowVectors.t.sol  (Solidity _computePayment)

import { writeFileSync } from "fs";
import { join } from "path";
import {
  deriveTaskOutcome,
  computePayment,
  computeChallengeBond,
  TaskOutcomeKind,
  TaskScenario,
  MAX_SCORE,
} from "../sdk/task-outcome-oracle";

const THRESHOLD = 200_000;
const ESCROWS = [1_000_000_000n, 360_000_007n]; // round SOL + a non-round value
const FEE_BPS = [1000, 0, 2500];
// Score boundaries: below, threshold−1, threshold, mid, MAX, and a kind-1 pair.
const SCORES = [1, THRESHOLD - 1, THRESHOLD, 600_000, MAX_SCORE];
const MULTIPLIERS = [2, 10];
const SLASH_BPS = [5000, 3000];

interface Vector {
  scenario: {
    escrowLamports: string;
    qualityThreshold: number;
    protocolFeeBps: number;
    compositeScore: number;
    verificationKind: 0 | 1;
    challengeBondMultiplier: number;
    bondSlashTreasuryBps: number;
    outcome: number;
  };
  payment: string;
  fee: string;
  remainder: string;
  bond: string;
  payout: {
    agentLamports: string;
    treasuryLamports: string;
    clientLamports: string;
    challengerLamports: string;
  };
}

const vectors: Vector[] = [];

function push(s: TaskScenario): void {
  const { payment, fee, remainder } = computePayment(
    s.compositeScore,
    s.qualityThreshold,
    s.escrowLamports,
    s.protocolFeeBps
  );
  const bond = computeChallengeBond(
    s.escrowLamports,
    s.challengeBondMultiplier
  );
  const payout = deriveTaskOutcome(s);
  vectors.push({
    scenario: {
      escrowLamports: s.escrowLamports.toString(),
      qualityThreshold: s.qualityThreshold,
      protocolFeeBps: s.protocolFeeBps,
      compositeScore: s.compositeScore,
      verificationKind: s.verificationKind,
      challengeBondMultiplier: s.challengeBondMultiplier,
      bondSlashTreasuryBps: s.bondSlashTreasuryBps,
      outcome: s.outcome,
    },
    payment: payment.toString(),
    fee: fee.toString(),
    remainder: remainder.toString(),
    bond: bond.toString(),
    payout: {
      agentLamports: payout.agentLamports.toString(),
      treasuryLamports: payout.treasuryLamports.toString(),
      clientLamports: payout.clientLamports.toString(),
      challengerLamports: payout.challengerLamports.toString(),
    },
  });
}

// Kind-0 (oracle) continuum across the outcome families.
for (const escrow of ESCROWS) {
  for (const feeBps of FEE_BPS) {
    for (const score of SCORES) {
      for (const outcome of [
        TaskOutcomeKind.Finalized,
        TaskOutcomeKind.ResolvedAgentWins,
        TaskOutcomeKind.ResolvedChallengerWins,
        TaskOutcomeKind.DefaultResolved,
        TaskOutcomeKind.Expired,
      ]) {
        push({
          escrowLamports: escrow,
          qualityThreshold: THRESHOLD,
          protocolFeeBps: feeBps,
          compositeScore: score,
          verificationKind: 0,
          challengeBondMultiplier: MULTIPLIERS[0],
          bondSlashTreasuryBps: SLASH_BPS[0],
          outcome,
        });
      }
    }
  }
}

// Bond-parameter sweep (multiplier × slash bps) on the agent-wins path where
// they matter, at a fixed mid score.
for (const mult of MULTIPLIERS) {
  for (const bps of SLASH_BPS) {
    push({
      escrowLamports: ESCROWS[0],
      qualityThreshold: THRESHOLD,
      protocolFeeBps: FEE_BPS[0],
      compositeScore: 600_000,
      verificationKind: 0,
      challengeBondMultiplier: mult,
      bondSlashTreasuryBps: bps,
      outcome: TaskOutcomeKind.ResolvedAgentWins,
    });
  }
}

// Kind-1 (attested) binary pair across the outcome families.
for (const score of [0, MAX_SCORE]) {
  for (const outcome of [
    TaskOutcomeKind.Finalized,
    TaskOutcomeKind.ResolvedAgentWins,
    TaskOutcomeKind.DefaultResolved,
    TaskOutcomeKind.Expired,
  ]) {
    push({
      escrowLamports: ESCROWS[0],
      qualityThreshold: THRESHOLD,
      protocolFeeBps: FEE_BPS[0],
      compositeScore: score,
      verificationKind: 1,
      challengeBondMultiplier: MULTIPLIERS[0],
      bondSlashTreasuryBps: SLASH_BPS[0],
      outcome,
    });
  }
}

const out = {
  _comment:
    "GENERATED by scripts/gen-task-payout-vectors.ts — do not hand-edit. " +
    "Pins the Shillbot payout formula across TS (sdk/task-outcome-oracle.ts), " +
    "Rust (scoring.rs + resolve_challenge.rs), and Solidity (ShillbotEscrow.sol).",
  maxScore: MAX_SCORE,
  count: vectors.length,
  vectors,
};

const path = join(
  __dirname,
  "..",
  "tests",
  "fixtures",
  "task-payout-vectors.json"
);
writeFileSync(path, JSON.stringify(out, null, 2) + "\n");
console.log(`wrote ${vectors.length} vectors to ${path}`);
