#!/usr/bin/env node
// Converts verifying_key.json (snarkjs output) to a Rust constant file
// compatible with groth16-solana's Groth16Verifyingkey struct.
//
// Output: ../../programs/coordination/src/verifying_key.rs
//
// Byte format for groth16-solana (Ethereum altbn128 precompile convention):
//   G1 point: X_be (32 bytes) || Y_be (32 bytes)                     = 64 bytes
//   G2 point: X.c1_be (32) || X.c0_be (32) || Y.c1_be (32) || Y.c0_be (32) = 128 bytes
//
// In snarkjs JSON:
//   G1 = ["0x<X>", "0x<Y>", "1"]
//   G2 = [["0x<Xc0>", "0x<Xc1>"], ["0x<Yc0>", "0x<Yc1>"], ["1","0"]]
//   Note: snarkjs orders Fp2 coords as [c0, c1]; altbn128 precompile wants [c1, c0].

"use strict";

const fs = require("fs");
const path = require("path");

const VK_JSON = path.join(__dirname, "verifying_key.json");
const OUT_RS = path.join(__dirname, "verifying_key.rs");

function hexToBytes32(val) {
    // snarkjs may export as decimal string or 0x-prefixed hex string
    const hex = val.startsWith("0x")
        ? val.slice(2)
        : BigInt(val).toString(16);
    const buf = Buffer.from(hex.padStart(64, "0"), "hex");
    if (buf.length !== 32) throw new Error(`Expected 32 bytes, got ${buf.length} for ${val}`);
    return buf;
}

function g1ToBytes(point) {
    return Buffer.concat([hexToBytes32(point[0]), hexToBytes32(point[1])]);
}

// snarkjs G2: [[c0, c1], [c0, c1], ...]; altbn128 wants [c1, c0] for each coord.
function g2ToBytes(point) {
    return Buffer.concat([
        hexToBytes32(point[0][1]), // X.c1
        hexToBytes32(point[0][0]), // X.c0
        hexToBytes32(point[1][1]), // Y.c1
        hexToBytes32(point[1][0]), // Y.c0
    ]);
}

function toRustByteArray(buf) {
    return Array.from(buf).join(", ");
}

const vk = JSON.parse(fs.readFileSync(VK_JSON, "utf8"));

if (vk.protocol !== "groth16") throw new Error(`Expected groth16, got ${vk.protocol}`);
if (vk.curve !== "bn128") throw new Error(`Expected bn128, got ${vk.curve}`);

const nPublic = vk.nPublic;
const alphaG1 = g1ToBytes(vk.vk_alpha_1);
const betaG2 = g2ToBytes(vk.vk_beta_2);
const gammaG2 = g2ToBytes(vk.vk_gamma_2);
const deltaG2 = g2ToBytes(vk.vk_delta_2);
const ic = vk.IC.map(g1ToBytes);

if (ic.length !== nPublic + 1) {
    throw new Error(`IC length mismatch: expected ${nPublic + 1}, got ${ic.length}`);
}

const icEntries = ic
    .map((buf) => `        [\n            ${toRustByteArray(buf)},\n        ]`)
    .join(",\n");

const out = `// AUTO-GENERATED by circuits/bool_range/export_vk.js
// Re-run circuits/bool_range/setup.sh to regenerate.
// DO NOT EDIT BY HAND.

use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${nPublic},

    vk_alpha_g1: [
        ${toRustByteArray(alphaG1)},
    ],

    vk_beta_g2: [
        ${toRustByteArray(betaG2)},
    ],

    vk_gamme_g2: [
        ${toRustByteArray(gammaG2)},
    ],

    vk_delta_g2: [
        ${toRustByteArray(deltaG2)},
    ],

    vk_ic: &[
${icEntries},
    ],
};
`;

fs.writeFileSync(OUT_RS, out, "utf8");
console.log(`Written: ${OUT_RS}`);
console.log(`  nr_pubinputs: ${nPublic}, IC entries: ${ic.length}`);
